CREATE TABLE EMPLOYEE(
	ID 			NUMBER(2),
	F_NAME 	VARCHAR(30),
	L_NAME 	VARCHAR(30),
	DEPT 		VARCHAR(10),
	SALARY	NUMBER(5),
	DOJ			DATE,
	ADDRESS	VARCHAR(15),
	MARRIED CHAR(1)
);
	
INSERT INTO EMPLOYEE
VALUES(1, 'VINAY', 'KUMAR', 'MCA', 25000, '27-sep-2001', 'GHAZIABAD', 'Y');

INSERT INTO EMPLOYEE
VALUES(2, 'SUMAN', 'VERMA', 'MCA', 15000, '17-oct-2006', 'MERRUT', 'Y');

INSERT INTO EMPLOYEE
VALUES(3, 'AKASH', 'SINGH', 'CS', 20000, '15-jan-2005', 'KANPUR', 'Y');

INSERT INTO EMPLOYEE
VALUES(4, 'SAGAR', 'KUMAR', 'IT', 20000, '12-feb-2019', 'GHAZIABAD', 'N');

INSERT INTO EMPLOYEE
VALUES(5, 'ROHAN', 'SHARMA', 'CS', 21000, '18-sep-2005', 'GHAZIABAD');

INSERT INTO EMPLOYEE
VALUES(6, 'ROBIN', 'SINGH', 'IT', 18000, '22-oct-2021', 'MERRUT', 'N');

INSERT INTO EMPLOYEE
VALUES(7, 'AKASH', 'RANJAN', 'CS', 22000, '14-nov-2019', 'GHAZIABAD');

SELECT * FROM EMPLOYEE
WHERE ADDRESS = 'GHAZIABAD';

SELECT DISTINCT DEPT FROM EMPLOYEE;

SELECT ID, (F_NAME || ' ' || L_NAME) AS NAME, DEPT FROM EMPLOYEE;

SELECT F_NAME || ' is working in ' || DEPT || ' Department' AS OUTPUT FROM EMPLOYEE;

SELECT F_NAME || ' ' || L_NAME AS NAME FROM EMPLOYEE
WHERE DOJ > '15-jan-2005';

UPDATE EMPLOYEE
SET SALARY = 25000 WHERE ID = 2;

SELECT ID, (F_NAME || ' ' || L_NAME) AS NAME, (SALARY * 12) AS "ANNUAL SALARY" FROM EMPLOYEE;

SELECT ID, (F_NAME || ' ' || L_NAME) AS NAME, DEPT, (SALARY + 300) AS "GROSS SALARY", DOJ, ADDRESS, MARRIED FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 15000 AND 30000;

SELECT * FROM EMPLOYEE
WHERE DOJ BETWEEN TO_DATE('27-09-2001', 'DD/MM/YYYY') AND TO_DATE('12-02-2019', 'DD/MM/YYYY');

SELECT * FROM EMPLOYEE
WHERE DEPT IN ('MCA', 'CS');

SELECT * FROM EMPLOYEE
WHERE DEPT <> 'MCA';

SELECT * FROM EMPLOYEE
WHERE F_NAME LIKE 'R%';

SELECT * FROM EMPLOYEE
WHERE F_NAME LIKE 'RO%';

SELECT * FROM EMPLOYEE
WHERE F_NAME LIKE 'R____%';

SELECT * FROM EMPLOYEE
WHERE F_NAME LIKE '_O%';

SELECT * FROM EMPLOYEE
WHERE MARRIED = 'Y';

SELECT * FROM EMPLOYEE
WHERE MARRIED = 'N';

SELECT * FROM EMPLOYEE
WHERE MARRIED IS NULL;

SELECT * FROM EMPLOYEE
WHERE DEPT = 'MCA' AND MARRIED = 'Y';
