CREATE TABLE PRODUCT_MASTER(
PRODUCTNO						VARCHAR2(6)	,	
DESCRIPTION						VARCHAR2(15),	
PROFITPERCENT		NUMBER(4,2),
UNITMEASURE					VARCHAR2(10),	
QTYONHAND						NUMBER(8),		
REORDERLVL						NUMBER(8,2),
SELLPRICE						NUMBER(8,2),
COSTPRICE						NUMBER(8,2)
);

INSERT INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION, PROFITPERCENT, UNITMEASURE, QTYONHAND	,REORDERLVL, SELLPRICE, COSTPRICE) VALUES('P00001',	'1.44floppies' ,5	,	'Piece'	,	200	,50	,350, 250);

INSERT INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION, PROFITPERCENT, UNITMEASURE, QTYONHAND	,REORDERLVL, SELLPRICE, COSTPRICE) VALUES('P03453','Monitors', 6, 'Piece'	,150	,50, 500,	350);

INSERT INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION, PROFITPERCENT, UNITMEASURE, QTYONHAND	,REORDERLVL, SELLPRICE, COSTPRICE) VALUES('P06734','Mouse' ,5	,'Piece'	,100, 20, 600	,450); 

INSERT INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION, PROFITPERCENT, UNITMEASURE, QTYONHAND	,REORDERLVL, SELLPRICE, COSTPRICE) VALUES('P07865','1.22floppies', 5,'Piece',100,	20,750,500);

INSERT INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION, PROFITPERCENT, UNITMEASURE, QTYONHAND	,REORDERLVL, SELLPRICE, COSTPRICE) VALUES('P07868',	'Keyboards' ,2	,'Piece',150, 50, 850	,550);

INSERT INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION, PROFITPERCENT, UNITMEASURE, QTYONHAND	,REORDERLVL, SELLPRICE, COSTPRICE) VALUES('P07885','CDDrive',2.5,'Piece',80	,30	,700	,450);

INSERT INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION, PROFITPERCENT, UNITMEASURE, QTYONHAND	,REORDERLVL, SELLPRICE, COSTPRICE) VALUES('P07965',	'540 HDD', 4,	'Piece',100,40, 350	,250);

INSERT INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION, PROFITPERCENT, UNITMEASURE, QTYONHAND	,REORDERLVL, SELLPRICE, COSTPRICE) VALUES('P07975', '1.44Drive' ,5	,'Piece',	70, 30, 300	,175);

INSERT INTO PRODUCT_MASTER(PRODUCTNO,DESCRIPTION, PROFITPERCENT, UNITMEASURE, QTYONHAND	,REORDERLVL, SELLPRICE, COSTPRICE) VALUES('P08865', '1.22Drive', 5,	'Piece',75,30,450,300);

SELECT NAME FROM CLIENT_MASTER;

SELECT NAME,CITY FROM CLIENT_MASTER;

SELECT DESCRIPTION FROM PRODUCT_MASTER;

SELECT * FROM CLIENT_MASTER WHERE CITY='BOMBAY';

SELECT * FROM CLIENT_MASTER WHERE CLIENTNO IN('C00001','C000002');

SELECT * FROM PRODUCT_MASTER WHERE DESCRIPTION IN('1.44DRIVE','1.22DRIVE');

SELECT * FROM PRODUCT_MASTER WHERE SELLPRICE>5000;

SELECT * FROM CLIENT_MASTER WHERE CITY IN('BOMBAY','DELHI','MADRAS');

SELECT * FROM PRODUCT_MASTER WHERE SELLPRICE>2000 AND SELLPRICE<5000 ;

SELECT NAME, STATE, CITY FROM CLIENT_MASTER WHERE STATE <> 'Maharashtra';

UPDATE PRODUCT_MASTER
SET SELLPRICE=1150

WHERE DESCRIPTION='1.44floppies';
DELETE FROM CLIENT_MASTER

WHERE CLIENTNO='C00001';

SELECT PRODUCTNO, DESCRIPTION,SELLPRICE*15 AS NEW_SELLING_PRICE FROM PRODUCT_MASTER WHERE SELLPRICE>1500;

SELECT * FROM CLIENT_MASTER WHERE CITY LIKE '_A%';

SELECT * FROM CLIENT_MASTER WHERE NAME LIKE '_A%';

SELECT * FROM PRODUCT_MASTER ORDER BY DESCRIPTION;

SELECT SUM(REORDERLVL) FROM PRODUCT_MASTER;

SELECT AVG(COSTPRICE) FROM PRODUCT_MASTER;

SELECT MIN(COSTPRICE) FROM PRODUCT_MASTER;

SELECT MAN(COSTPRICE)MAX_PRICE,  MIN(COSTPRICE)MIN_PRICE FROM PRODUCT_MASTER;

SELECT COUNT(PRODUCTNO) FROM PRODUCT_MASTER WHERE SELLPRICE>=1500;

SELECT * FROM PRODUCT_MASTER ORDER BY SELLPRICE;

SELECT * FROM PRODUCT_MASTER ORDER BY SELLPRICE DESC;
