CREATE TABLE PRODUCT_MASTER
( PRODUCT_NO VARCHAR(6),
	DESCRIPTION VARCHAR(20),
	PROFIT_PERCENTAGE NUMBER(6),
	UNIT_MEASURE VARCHAR(10),
	QTY_ON_HAND NUMBER(6),
	REORDER_LVL NUMBER(6),
	SELL_PRICE NUMBER(7, 2),
	COST_PRICE NUMBER(7,2)
);