CREATE TABLE CLIENT_MASTER
( CLIENT_NO VARCHAR(6),
	NAME VARCHAR(20),
	ADDRESS1 VARCHAR(30),
	ADDRESS2 VARCHAR(30),
	CITY VARCHAR(15),
	STATE VARCHAR(15),
	PINCODE NUMBER(6),
	BAL_DUE NUMBER(10,2)
);
   