CREATE TABLE CLIENT_MASTER
( CLIENTNO VARCHAR(6),
	NAME VARCHAR(30),
	CITY VARCHAR(10),
	PINCODE NUMBER(6),
	STATE VARCHAR(30),
	BALDUE NUMBER(6)
);
INSERT INTO CLIENT_MASTER
(CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
VALUES('C00001', 'Ivan Bayross', 'Mumbai', 400054, 'Maharashtra', 15000);
INSERT INTO CLIENT_MASTER
(CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
VALUES('C00002', 'Mamta Mazumdar', 'Madras', 780001, 'Tamil Nadu', 0);
INSERT INTO CLIENT_MASTER
(CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
VALUES('C00003', 'Chhaya Bankar', 'Mumbai', 400057, 'Maharashtra', 5000);
INSERT INTO CLIENT_MASTER
(CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
VALUES('C00004', 'Ashwini Joshi', 'Bangalore', 560001, 'Karnataka', 0);
INSERT INTO CLIENT_MASTER
(CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
VALUES('C00005', 'Hansel Colaco', 'Mumbai', 400060, 'Maharashtra', 2000);
INSERT INTO CLIENT_MASTER
(CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
VALUES('C00006', 'Deepak Sharma', 'Mangalore', 560050, 'Karnataka', 0);